package com.techmorphosis.qube.utils;

/**
 * Created by Kamlesh on 028 28/12/15.
 */
public enum ITEM_VIEW_TYPE {
    DRAWER_ITEM_VIEW, SEARCH_LISTING_ITEM_VIEW, SINGLE_TEXT_VIEW, PROP_LOCATION_ITEM_VIEW, FLOOR_ITEM_VIEW, UPLOAD_ITEM_VIEW, TAG_VIEW, PROPERTY_PICKS_ITEM_VIEW
    , SHORTLIST_ITEM_VIEW, YOUR_LISTING_VIEW, BROKER_ENQUIRY_VIEW, YOUR_REQUIREMENT_VIEW, NOTIFICATION_VIEW;
}
